### ISSUE TITLE
Let's try again...

### ISSUE THREAD

**Issue by Zibri** [evilsocket/evilbts#6]
Calma... :D   ci stavo arrivando..

Makefile:120: recipe for target 'Sgsn.o' failed
make[2]: *** [Sgsn.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/zibri/evilbts/yatebts/mbts/SGSNGGSN'
Makefile:140: recipe for target '../SGSNGGSN/libSGSNGGSN.a' failed
make[1]: *** [../SGSNGGSN/libSGSNGGSN.a] Error 2
ar rcs libsqlite3.a sqlite3.o
make[2]: Leaving directory '/home/zibri/evilbts/yatebts/mbts/sqlite3'
make[1]: Leaving directory '/home/zibri/evilbts/yatebts/mbts/apps'
Makefile:53: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by evilsocket** [comment]
Sono calmissimo, hai comunque toppato a chi riportare la cosa, non ho scritto io il sw.
